### ISSUE TITLE
How to use this in Ubuntu terminal?

### ISSUE THREAD

**Issue by gpk2000** [ketankr9/cses-cli#1]

**Comment by ketankr9** [comment]
* Download the binary [for ubuntu 64bit](https://github.com/ketankr9/cses-cli/releases/download/v0.1-beta.1/cses-cli_0.1b_linux_amd64) or [for ubuntu 32bit](https://github.com/ketankr9/cses-cli/releases/download/v0.1-beta.1/cses-cli_0.1b_linux_386)  
* Install lynx
* Rename the binary to cses-cli and move it to PATH
* Just type these command in the terminal one by one and you will understand
```
cses-cli login
cses-cli list
cses-cli show 1742
cses-cli solve 1742
cses-cli submit 1742.task.cpp
```


Please refer to the release section. [https://github.com/ketankr9/cses-cli/releases](https://github.com/ketankr9/cses-cli/releases)  for more.

**Comment by ketankr9** [comment]
I have updated the [Readme](https://github.com/ketankr9/cses-cli/blob/master/README.md) now with complete detail.

**Comment by gpk2000** [comment]
Thank you for this :)
